name: fruit_shop_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  svg_flutter: ^0.0.1
  carousel_slider: ^4.2.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  jumping_dot: ^0.0.7
  dartz: ^0.10.1
  build_runner: ^2.4.11
  cloud_firestore: ^5.1.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  webview_flutter: ^4.8.0
  flutter_super_html_viewer: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bottom_nav/
    - assets/app_bar/
    - assets/animations/
    - assets/slider/
    - assets/static banner/
    - assets/drawer/

flutter_launcher_icons:
  android: "launcher_icon"  # Default resource name (optional)
  ios: true                 # Default, enable iOS icon generation (optional)
  image_path: "assets/ic_launcher.png"  # Default, path to app icon image (optional)
  round_icon: true
