// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6f_1TfsdC18V6E9VZU46GPttxVnjEe8o',
    appId: '1:130659922072:web:0085aa68915f69adcba0ed',
    messagingSenderId: '130659922072',
    projectId: 'appdistribution-f59e9',
    authDomain: 'appdistribution-f59e9.firebaseapp.com',
    storageBucket: 'appdistribution-f59e9.appspot.com',
    measurementId: 'G-1724LM1G8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAC64eQzk7UolA9wEiPzRZbChlN_uK67s',
    appId: '1:130659922072:android:618623653a3002a8cba0ed',
    messagingSenderId: '130659922072',
    projectId: 'appdistribution-f59e9',
    storageBucket: 'appdistribution-f59e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJPjH2I9need7jxBNtjiSdpOPib_kaFcQ',
    appId: '1:130659922072:ios:7ccdf62197c69466cba0ed',
    messagingSenderId: '130659922072',
    projectId: 'appdistribution-f59e9',
    storageBucket: 'appdistribution-f59e9.appspot.com',
    iosBundleId: 'com.example.fruitShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJPjH2I9need7jxBNtjiSdpOPib_kaFcQ',
    appId: '1:130659922072:ios:7ccdf62197c69466cba0ed',
    messagingSenderId: '130659922072',
    projectId: 'appdistribution-f59e9',
    storageBucket: 'appdistribution-f59e9.appspot.com',
    iosBundleId: 'com.example.fruitShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6f_1TfsdC18V6E9VZU46GPttxVnjEe8o',
    appId: '1:130659922072:web:ab212adb6ae0609ecba0ed',
    messagingSenderId: '130659922072',
    projectId: 'appdistribution-f59e9',
    authDomain: 'appdistribution-f59e9.firebaseapp.com',
    storageBucket: 'appdistribution-f59e9.appspot.com',
    measurementId: 'G-6EZP4VYJRZ',
  );
}
